### ISSUE TITLE
Plugin states "Zotero not found" because it is on port 24119 instead of 23119

### ISSUE THREAD

**Issue by gautampk** [jannessm/joplin-zotero-link#3]
My Zotero server appears to be running on port 24119, not port 23119.  You can check the port Zotero is running on by looking at the config file of the browser plugin (Options > Advanced > Config Editor).

As a workaround, I will try to manually unpack the plugin and change the relevant bits of the JS file, but it might be nice to have a way to change the port from the front end :)

**Comment by gautampk** [comment]
P.S. I have no idea why it is on port 24119 or how to change it from Zotero

**Comment by jannessm** [comment]
Sorry for my late reply. Regarding to the documentation of https://github.com/MunGell/ZotServer, it should run on 23119. Have you changed anything regarding the server manually?

**Comment by MunGell** [comment]
Hi, I will add my 2c since this is related to the ZotServer plugin... sort of.

I've done a little bit of research and it sounds like @gautampk doesn't use Zotero ([code](https://github.com/zotero/zotero/blob/a612c1227efd3adbfec86a854e97ce751f24c1f8/defaults/preferences/zotero.js#L146)), but rather [Juris-M](https://juris-m.github.io) ([code](https://github.com/Juris-M/zotero/blob/a5bfb1e49aa3618ad1b1a3daaa792b835507f942/defaults/preferences/zotero.js#L167)) which indeed runs its server on port 24119.

I personally was not aware of this difference in these sister products until now. If this is a valid use case, port number might need to be configurable in extension.

**Comment by jannessm** [comment]
Thank you for pointing that out!

**Comment by jannessm** [comment]
Please checkout my new version. I tested the plugin now more in depth and added a setting to configure the port as wished.
